version: "3.9"

services:
  app:
    build: .
    container_name: book-recommender-app
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    environment:
      - API_URL=http://127.0.0.1:8000